language: node_js
node_js:
  - "node"
  - "6"
  - "6.1"
  - "5.11"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g node-inspector
  - npm install -g mocha
  - npm install -g node-gyp
  - npm install -g asar